name: CI

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: Modflower/.github/workflows/mod-build.yml@main
    with:
      artifacts: |
        '*/build/libs/'
